name: SemVer Release Version
description: Utilized for creating releases of projects

# Inputs
inputs:
  nexus_repo_id:
    description: "Nexus Repository ID" 
    required: false
    default: "maven-snapshots"
  nexus_repo_username:
    description: "Nexus Repository Username" 
    required: false 
    default: "admin"
  is_tag:
    description: "Check if running on tag"
    required: false
    default: 'false'
  nexus_repo_password:
    description: "Nexus Repository Password"  
    required: true
  nexus_repo_url:
    description: "Nexus Repository URL"
    required: false 
    default: "https://nexus.tinkarbuild.com" 
  github_token:
    description: "GitHub Token"
    required: true
  gpg_passphrase:
    description: "GPG Passphrase"
    required: true
  gpg_key:
    description: "GPG Key"
    required: true
  ossrh_username:
    description: "OSSRH USERNAME"
    required: true
  ossrh_token:
    description: "OSSRH Token"
    required: true
  branch_name: 
    description: "Branch Name" 
    required: true 
  sonarcloud_token:
    description: "Token For Sonarcloud"
    required: false
  sonarcloud_host_url:     
    description: "Sonarcloud Host URL"
    required: false
    default: 'https://sonarcloud.io/'
  sonarcloud_organization:
    description: "Organization Name on Sonarcloud "
    required: false
    default: 'ikmdev'
  sonarcloud_sources:
    description: "source folder"
    required: false
    default: 'src/main/java'
  sonarcloud_projectKey:
    description: "Sonar project key"
    required: false
  sonarcloud_coverage_jacoco_xmlReportPaths:
    description: "Jacoco reports path"
    required: false
    default: 'target/site/jacoco/jacoco.xml'
  sonarcloud_java_binaries:
    description: "Java binaries folder"
    required: false      
    default: 'target/classes'   
  sonarcloud_tests:
    description: "Java test folder"
    required: false
    default: 'src/test/java'
  java_version:
    description: "Java Version"
    required: false 
    default: "23"

outputs:
  release_upload_url:
    description: "Release Url"
    value: ${{ steps.create_release.outputs.upload_url }}
  is_tag:
     description: "Is Tag"
     value: ${{ steps.is_tag.outputs.IS_TAG }}


runs:
  using: "composite"
  steps:
     - name: Setup Java
       uses: actions/setup-java@v4
       with:
            distribution: 'zulu'
            java-version: ${{inputs.java_version}}
            server-id: ossrh
            server-username: MAVEN_USERNAME
            server-password: MAVEN_CENTRAL_TOKEN
            gpg-private-key: ${{inputs.gpg_key}}
            gpg-passphrase: MAVEN_GPG_PASSPHRASE

     - name: Check For Tag
       id: is_tag
       shell: bash
       run: |
         if git show-ref --tags --verify --quiet "refs/tags/${HEAD_BRANCH}"; then
            echo "Tag ${HEAD_BRANCH} exists"
            echo "NEXUS_REPO_ID=maven-releases">> $GITHUB_OUTPUT
            echo "RELEASE_ENFORCEMENT=-Prelease-enforcement" >> $GITHUB_OUTPUT
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${HEAD_BRANCH} does not exist"
            echo "NEXUS_REPO_ID=maven-snapshots">> $GITHUB_OUTPUT
            echo "RELEASE_ENFORCEMENT=" >> $GITHUB_OUTPUT
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi
       env:
         HEAD_BRANCH: ${{ inputs.branch_name }}

     - name: Validate If Triggered By IKMDEV
       id: triggered_by_ikm
       shell: bash
       run: |
         echo "Repo Owner: ${REPOSITORY_OWNER}"
         echo "Trigger User: ${TRIGGER_USER}"

         if [ $REPOSITORY_OWNER == $TRIGGER_USER ]; then
           echo "IKM_TRIGGER=true" >> $GITHUB_OUTPUT
         else
           echo "IKM_TRIGGER=false" >> $GITHUB_OUTPUT
         fi
       env:
         REPOSITORY_OWNER: ${{github.repository_owner}}
         TRIGGER_USER: ${{github.event.workflow_run.head_repository.owner.login}}
        

     - name: Maven Settings File
       uses: whelk-io/maven-settings-xml-action@v22
       with:
        servers: '[{"id": "${{ steps.is_tag.outputs.NEXUS_REPO_ID }}", "username": "${{inputs.nexus_repo_username}}", "password": "${{inputs.nexus_repo_password}}"}]'
        profiles: '[{"id": "${{inputs.nexus_profile}}", "properties": {"altDeploymentRepository": "${{  steps.is_tag.outputs.NEXUS_REPO_ID  }}::${{ inputs.nexus_repo_url }}/repository/${{ steps.is_tag.outputs.NEXUS_REPO_ID  }}"}}]'
        active_profiles: '["${{inputs.nexus_profile}}"]' 
        output_file: .m2/settings.xml

     - name: Maven Build
       shell: bash
       run: |
          ./mvnw clean install\
            --batch-mode \
            -U \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -Dmaven.build.cache.enabled=false \
            -PcodeQuality \
						-PgenerateData \
            ${{  steps.is_tag.outputs.RELEASE_ENFORCEMENT  }}

     - name: SonarCloud Build and analyze
       shell: bash  
       run: | 
           ./mvnw verify sonar:sonar \
             --batch-mode \
             -Dmaven.build.cache.enabled=false \
             -Dsonar.sonarcloud_token=${{ inputs.sonarcloud_token }} \
             -Dsonar.organization=${{ github.repository_owner }} \
             -Dsonar.sonarcloud_host_url=${{ inputs.sonarcloud_host_url }} \
             -Dsonar.sources=${{ inputs.sonarcloud_sources }} \
             -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
             -Dsonar.coverage.jacoco.xmlReportPaths=${{ inputs.sonarcloud_coverage_jacoco_xmlReportPaths }} \
             -Dsonar.java.binaries=${{ inputs.sonarcloud_java_binaries }} \
             -Dsonar.tests=${{ inputs.sonarcloud_tests }}
       env:
        SONAR_TOKEN: ${{ inputs.sonarcloud_token }}
        SONAR_HOST_URL: ${{ inputs.sonarcloud_host_url }}
        SONAR_ORGANIZATION: ${{ github.repository_owner }} 

     - name: Deploy To Nexus
       shell: bash
       run: |
          ./mvnw deploy \
            --batch-mode \
            -U \
            -e \
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
            -DskipTests \
            -DskipITs \
            -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml'\
            -DrepositoryId='${{ steps.is_tag.outputs.NEXUS_REPO_ID  }}'
    
     - name: Publish To OSSRH (Maven Central Staging)
       shell: bash
       if: steps.is_tag.outputs.IS_TAG == 'true' && steps.triggered_by_ikm.outputs.IKM_TRIGGER == 'true' && !contains(github.event.repository.name, 'komet')
       run: |
            ./mvnw deploy \
                  --batch-mode \
                  -e \
                  -U \
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                  -DskipTests \
                  -DskipITs \
                  -Dmaven.main.skip \
                  -Dmaven.test.skip \
                  -DrepositoryId=ossrh \
                  -DrepositoryIdOSSRH='true' \
                  -PstageOSSRH \
                  -Dmaven.build.cache.enabled=false
       env:
          MAVEN_USERNAME: ${{ inputs.ossrh_username }}
          MAVEN_CENTRAL_TOKEN: ${{ inputs.ossrh_token }}
          MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}

     - name: Create Release
       id: create_release
       if: steps.is_tag.outputs.IS_TAG == 'true' && steps.triggered_by_ikm.outputs.IKM_TRIGGER == 'true'
       uses: comnoco/create-release-action@v2.0.5
       env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
       with:
          tag_name: ${{ inputs.branch_name }}
          release_name: Release ${{ inputs.branch_name }}
          body: |
            Release ${{ inputs.branch_name }}
          draft: false
          prerelease: false

     
